coolsnowwolf/luci

protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_ppp.lua, protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppoa.lua, protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppoe.lua, protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppossh.lua, protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pptp.lua
isabling LCP echos by *not* setting "option keepalive" was broken in
OpenWrt since https://dev.archive.openwrt.org/ticket/2373.html so setting
"0" in LuCI had the effect of reverting back to "5, 1" while the help
suggested otherwise.
Support for "keepalive 0" was fixed with https://git.openwrt.org/555c59230
so align LuCI now to emit "option keepalive 0" instead of removing the
option when entering "0" in the gui.
=> luci-proto-ppp: align keepalive defaults with current OpenWrt

libs/luci-lib-jsonc/src/jsonc.c
=> luci-lib-jsonc: store large JSON integer values as Lua doubles

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.alidns.dns.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/pub.doh.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
- [DNSPod.cn: https://doh.pub/dns-query](https://cloud.tencent.com/developer/article/1668074)
- [AliDNS: https://dns.alidns.com/dns-query](https://developer.aliyun.com/article/757592)
=> luci-app-https-dns-proxy: add DNSPod.cn and AliDNS DOH providers

applications/luci-app-uhttpd/po/zh-cn/uhttpd.po
修复 **HTTPS 监听器**错误地显示为 **HTTP 监听器**的问题
=> luci-app-uhttpd: Fix typo error

modules/luci-base/luasrc/model/network.lua
修复问题：https://github.com/coolsnowwolf/lede/issues/6042
参考：https://github.com/openwrt/luci/commit/461df8b0dc1a9be5fb9e904d8cdc44c6d0cbd6c8
=> 修复ipv6地址固定显示为[prefix]::1的问题

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/mobile.css
默认主题的登录页在手机浏览器里访问时用户名和密码框长度不一致。
调整前：
调整后：
调整后对于强迫症患者更友好。
=> 调整默认主题手机版登录页面密码框宽度比用户名窄的问题

modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
=> luci-mod-admin-full: fix 'crontab-details' not found

applications/luci-app-dawn/Makefile, applications/luci-app-dawn/luasrc/controller/dawn.lua, applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_config.lua, applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_hearing_map.lua, applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_network.lua, applications/luci-app-dawn/luasrc/tools/ieee80211.lua, applications/luci-app-dawn/root/usr/share/rpcd/acl.d/luci-app-dawn.json
Dawn is a decentralized WiFi controller.
Just install dawn and the APs will find each other via umdns. They
periodically exchange information about connected clients, wireless
statistics and other needed information. With that, the daemon load
balances clients between different APs through association control.
Luci-app-dawn is the graphical user interface.
It allows to:
- Configure dawn
- View Wireless Network Overview
- View Hearing Map
The hearing map is the list of all probe requests seen from a client
from all APs that are running the controller.
=> luci-app-dawn: add luci app for dawn

modules/luci-base/luasrc/dispatcher.lua
登录相关cookie种在 `/cgi-bin/luci` 路径
在浏览器直接输入`openwrt.lan`进行2次登录，不带完整路径，会被要求重新输入用户名和密码
=> luci-base: redirect / to /cgi-bin/luci/ to avoid login

modules/luci-base/po/zh-cn/base.po, modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
这是luci支持部分，related to coolsnowwolf/lede#8909
=> 加强版dnsmasq补丁支持过滤type65 https和unknown类型dns请求

modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/system.lua
zram-swap包可选zstd为默认压缩算法,但界面没有显示,然后看内核日志还是以界面的为准了
=> 添加lz4hc和zstd的zram选项

applications/luci-app-verysync/root/etc/init.d/verysync
Fixed the problem that the service failed to start。
The problem is: 
~# service verysync start
Killed
~#
=> Fixed the problem that the verysync service failed to start。

applications/luci-app-n2n_v2/Makefile, applications/luci-app-n2n_v2/luasrc/model/cbi/n2n_v2.lua, applications/luci-app-n2n_v2/po/zh-cn/n2n_v2.po
supernode参数用于客户端在dhcp模式下自动分配IP，便于使用
-a IP段 | 用于自动分配IP，格式如 -a 192.168.0.0-192.168.255.0/24
n2n_v2中也已同步更新
=> N2N服务器端dhcp设置

applications/luci-app-turboacc/root/etc/init.d/turboacc
We may need to disable MTK HWNAT in some cases, however, ```start()``` calls ```initial_conf()``` where ```$hw_flow``` is always set true when mtkhnat.ko is present. Therefore ```rmmod mtkhnat``` in ```stop()``` makes no sense because when ```start``` is called mtkhnat.ko will always be loaded.
PS:
May be inital_conf should be renamed intial_conf?
PS:
In line 3 of turboacc_status.htm, ```/etc/init.d/turboacc check_status fastpath``` may return empty value when xhr is requsted just after stop() finishes, causing empty response.
It's not a big problem and I'm sorry that I can't find a way to fix that.
```
XHR.poll(5, '<%=luci.dispatcher.build_url("admin", "network", "turboacc", "status")%>', null, function(x, status) {
if ( x && x.status == 200 ) {
fastpath_state.innerHTML = …
```
=> luci-app-turboacc: fix hw_flow always true when mtkhnat.ko present

applications/luci-app-haproxy-tcp/root/etc/haproxy_init.sh
Haproxy still did not work after haproxy-tcp upgarde to v2.6.6.
`[haproxy.main()] FD limit (1024) too low for maxconn=2048/maxsock=4123. Please raise 'ulimit-n' to 4123 or more to avoid any trouble.`
Need to comment the `ulimit-n` and `maxconn`.
=> update init config

applications/luci-app-unblockmusic/luasrc/model/cbi/unblockmusic/unblockmusic.lua, applications/luci-app-unblockmusic/root/etc/init.d/unblockmusic, applications/luci-app-unblockmusic/root/usr/bin/UnblockNeteaseMusicCloud
luci-app-unblockmusic: add white mode:
This PR added the white mode to luci-app-unblockmusic, which allows users to only proxy specfic devices and bypass other devices. This PR also moved the function to get LAN address out of global scope, to avoid some compile errors (but not fatal).
luci-app-unblockmusic: fix cloud mode ssl cert error on other website:
This PR fixed the rare ssl certificate error when opening websites other than netease cloud music, especially when luci-app-unblockmusic is running for a long time. This is because the cloud script did not clean the IPs added to the proxy ipset, and those IPs can belong to other websites when time goes by.
=> luci-app-unblockmusic: add white mode & fix cloud mode ssl cert error on other website

applications/luci-app-music-remote-center/root/etc/init.d/owntone
`/etc/init.d/owntone`中start-stop-daemon参数缺失`-b`，无法在后台运行，owntone无法正确创建PID文件
Signed-off-by: Yu Hua <hue715@gmail.com>
=> luci-app-music-remote-center: add init missing parameter `-b`

applications/luci-app-qbittorrent/po/zh-cn/qbittorrent.po
qb里面根本就没用到"Generate Randomly"，而且还翻译成"默认端口：8999"，导致其他插件的翻译错误！
=> luci-app-qbittorrent: update zh-cn translation

applications/luci-app-ssrserver-python/root/usr/share/ssr/shadowsocks/lru_cache.py
change collections.MutableMapping to collections.abc.MutableMapping
This PR closes #225
=> luci-app-ssrserver-python:Fix server startup failure caused by Python library changes

applications/luci-app-mosdns/root/usr/share/mosdns/sp_low.tdata
Because the file contains a separate entry for "Site", all "*.site" domains cannot be resolved.
=> luci-app-mosdns: Fix ".site" domain name cannot be resolved

modules/luci-base/po/zh-cn/base.po, protocols/luci-proto-ipv6/Makefile, protocols/luci-proto-ipv6/luasrc/model/cbi/admin_network/proto_ipip6.lua, protocols/luci-proto-ipv6/luasrc/model/network/proto_4x6.lua
Add IPIP6(RFC2473) support
[coolsnowwolf/lede#11970](https://github.com/coolsnowwolf/lede/pull/11970)
=> luci-proto-ipv6: add ipip6 support

applications/luci-app-zerotier/root/etc/init.d/zerotier
Reverts coolsnowwolf/luci#269
https://github.com/coolsnowwolf/luci/commit/c0ab8ee0cf5e1f99075ae63bcec5298bef85830e
https://github.com/coolsnowwolf/lede/issues/11974
错误地删除了所有的配置文件，导致重启后无法恢复连接。
=> Revert "fix: /etc/config/zero are incorrectly written to flash"

applications/luci-app-mwan3/luasrc/view/mwan/status_detail.htm, applications/luci-app-mwan3/luasrc/view/mwan/status_diagnostics.htm, applications/luci-app-mwan3/luasrc/view/mwan/status_interface.htm, applications/luci-app-mwan3/luasrc/view/mwan/status_troubleshooting.htm
mwan3状态页面无限加载，经排查发现是mwan3状态的四个tab都没有加载cbi.js导致
=> luci-app-mwan3: fix status page issue

applications/luci-app-pptp-server/luasrc/model/cbi/pptp-server.lua
`Andriod` => `Android`
The po file [pptp.po](/coolsnowwolf/luci/blob/master/applications/luci-app-pptp-server/po/zh-cn/pptp.po) has fixed via 6113678abfc4b587b3e3d12517b54bd35d061819.
=> luci-app-pptp-server: fix typo error

modules/luci-mod-admin-full/luasrc/view/admin_network/wifi_join.htm
改进 WiFi 扫描结果页面的样式效果，调整为跟 `24.10` 一样的 table 结构。
> 主打一个新版有的旧版也能有，修修补补又三年！
> 信号强度居然没有直接显示！！怎么过的，这些年。
> 这下直观多了~~
=> luci-mod-admin-full: greatly improved WiFi scan page display

modules/luci-base/luasrc/dispatcher.lua
`18.06`的陈年 Bug，还是修复一下，主打一个`修修补补又三年`。
> inreq 的初始化问题，主要影响 `Network` 和 `Wireless` 两个页面的 TabMenu 渲染。
有这个 TabMenu，页面操作还是会方便很多：
=> luci-base: improve interface page display

applications/luci-app-ddns-go/Makefile, applications/luci-app-ddns-go/root/etc/config/ddns-go, applications/luci-app-ddns-go/root/etc/init.d/ddns-go, applications/luci-app-ddns-go/root/etc/uci-defaults/ddns-go-permissions
Used commit cfa7fb1 from 23.05, compiled successfully.
=> luci-app-ddns-go: add config and init 
