- modules/luci-base/luasrc/model/network.lua
- modules/luci-mod-admin-full/luasrc/view/admin_network/lease_status.htm
- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
1、修复状态页面和DHCP/DNS页面的租约列表中，主机名显示不全的bug
2、状态页面增加显示多WAN信息的功能
> 1、修复状态页面和DHCP/DNS页面的租约列表中，主机名显示不全，以及多wan信息显示的功能

- applications/luci-app-minidlna/luasrc/controller/minidlna.lua
- applications/luci-app-minidlna/luasrc/model/cbi/minidlna.lua
https://github.com/openwrt/packages/blob/3d9618c61b059e1984d6fcd664752adc18e236fd/multimedia/minidlna/Makefile#L64
New packages have changed the name.
> luci-app-minidlna: fix bug

- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
> luci: fix cpuinfo display on ARMv8 machine

- applications/luci-app-aria2/luasrc/view/aria2/overview_status.htm
让controller 和 html 模板 中的调用目标保持一致
> fix overview_status.htm

- modules/luci-base/luasrc/model/network.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
- modules/luci-mod-admin-mini/luasrc/model/cbi/mini/wifi.lua
这个是对应 https://github.com/coolsnowwolf/lede/pull/5844 的luci变更
> 闭源MT7615（K2P）支持原生Luci配置，支持多SSID

- modules/luci-mod-admin-full/luasrc/view/admin_network/diagnostics.htm
Fixes: https://github.com/coolsnowwolf/lede/issues/6645
> luci-mod-admin-full: fix check for traceroute6

- modules/luci-base/htdocs/luci-static/resources/cbi.js
Fixes https://github.com/coolsnowwolf/lede/issues/6613#issue-842551003
> Fix time display error

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/README.md
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices.disabled/linksys-ea9500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-e4200v2-ea4500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-e4200v2.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea3500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea4500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea6350v3.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea7300v1.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea7300v2.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8300.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-mr8300.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1200ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acs.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acv2.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt3200acm.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt32x.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/zyxel-nbg6817.lua
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/alternative_reboot.htm
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/applyreboot.htm
- applications/luci-app-advanced-reboot/po/es/advanced-reboot.po
- applications/luci-app-advanced-reboot/po/ru/advanced-reboot.po
- applications/luci-app-advanced-reboot/po/sv/advanced-reboot.po
- applications/luci-app-advanced-reboot/po/zh-cn/advanced-reboot.po
- applications/luci-app-advanced-reboot/po/zh-tw/advanced-reboot.po
- applications/luci-app-advanced-reboot/root/etc/uci-defaults/40_luci-advanced-reboot
Fix: https://github.com/coolsnowwolf/lede/issues/7118
> luci-app-advanced-reboot: backport devices support

- applications/luci-app-uhttpd/po/zh-cn/uhttpd.po
> luci-app-uhttpd: 修改中文翻译，优化视图显示

- applications/luci-app-watchcat/luasrc/controller/watchcat.lua
- applications/luci-app-watchcat/luasrc/model/cbi/watchcat/watchcat.lua
- applications/luci-app-watchcat/root/etc/uci-defaults/40_luci-watchcat
> fix watchcat config error

- applications/luci-app-easymesh/Makefile
- applications/luci-app-easymesh/root/etc/init.d/easymesh
> update easymesh v2.0

- protocols/luci-proto-vxlan/Makefile
- protocols/luci-proto-vxlan/luasrc/model/cbi/admin_network/proto_vxlan.lua
- protocols/luci-proto-vxlan/luasrc/model/cbi/admin_network/proto_vxlan6.lua
- protocols/luci-proto-vxlan/luasrc/model/network/proto_vxlan.lua
- protocols/luci-proto-vxlan/luasrc/model/network/proto_vxlan6.lua
参考了以下内容搬运来的：
https://github.com/openwrt/luci/tree/master/protocols/luci-proto-vxlan
https://github.com/coolsnowwolf/luci/tree/master/protocols/luci-proto-ipip
> luci-proto-vxlan: add new package

- modules/luci-mod-admin-full/luasrc/view/admin_network/lease_status.htm
> 显示优化：dhcp列表按IP地址排序

- applications/luci-app-unblockmusic/root/etc/init.d/unblockmusic
Add the missing SNAT rule to make local server mode going successfully.
> unblockmusic: fix local server cannot request

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
如标题所示：
不知道80211w是否确切的支持，如不支持请大佬删除！
Signed-off-by: nanchuci nanchuci023@gmail.com
> 增加mt7615_dbdc闭源驱动对80211k 80211v 80211r 80211w和wps的支持

- applications/luci-app-aliyundrive-webdav/Makefile
Ref: https://github.com/messense/aliyundrive-webdav/commit/876ff07fce522d6740cbd1b7270300f3eabb7b45#diff-3be1ca2389f4762c76ff03e47cd6b44c5246c432976a2336ce67c5f2fa47292a
> luci-app-aliyundrive-webdav: update to 1.5.1

- applications/luci-app-haproxy-tcp/root/etc/haproxy_init.sh
Fix haproxy did not work after  haproxy-tcp upgarde to v2.6.6.
> Fix haproxy init config bug in v2.6.6

- applications/luci-app-arpbind/Makefile
> fix LUCI_DEPENDS: ip to ip-full

- applications/luci-app-baidupcs-web/root/etc/init.d/baidupcs-web
Fixed the problem that the service failed to start  (Fix #179)
Signed-off-by: Yu Hua <hue715@gmail.com>
> luci-app-baidupcs-web: Fix startup error

- applications/luci-app-qbittorrent/luasrc/model/cbi/qbittorrent/webgui.lua
- applications/luci-app-qbittorrent/root/etc/config/qbittorrent
> luci-app-qbittorrent: Fixed changing language not taking effect

- applications/luci-app-adbyby-plus/luasrc/model/cbi/adbyby/advanced.lua
> luci-app-adbyby-plus: update DynamicList

- applications/luci-app-frpc/luasrc/model/cbi/frp/basic.lua
- applications/luci-app-frpc/luasrc/model/cbi/frp/config.lua
- applications/luci-app-frpc/po/zh-cn/frp.po
- applications/luci-app-frpc/root/etc/init.d/frp
添加了自定义TLS协议加密，以开启frpc与服务器端单向或双向验证
> luci-app-frpc: add custom tls protocol encryption

- applications/luci-app-fwknopd/root/usr/sbin/gen-qr.sh
Update gen-qr.sh for fix `qrencode: unrecognized option: I`
> luci-fwknopd: Update gen-qr.sh

- applications/luci-app-dockerman/luasrc/model/cbi/dockerman/containers.lua
- applications/luci-app-dockerman/luasrc/model/cbi/dockerman/networks.lua
https://github.com/coolsnowwolf/lede/issues/11960
https://github.com/coolsnowwolf/packages/issues/778
> luci-app-dockerman: fix network page issue

- applications/luci-app-zerotier/root/etc/init.d/zerotier
https://github.com/immortalwrt/luci/issues/363
> fix: /etc/config/zero are incorrectly written to flash

- applications/luci-app-cifs-mount/po/zh-cn/cifs.po
- applications/luci-app-v2ray-server/po/zh-cn/v2ray_server.po
- luci-app-v2ray-server
- luci-app-cifs-mount
> luci-app-v2ray-server & luci-app-cifs-mount: update translation

- applications/luci-app-pptp-server/po/zh-cn/pptp.po
fix: spelling errors
luci-app-pptp-server
> fix: spelling errors

- applications/luci-app-smartinfo/Makefile
- applications/luci-app-smartinfo/luasrc/controller/smartinfo.lua
- applications/luci-app-smartinfo/luasrc/model/cbi/smartinfo.lua
- applications/luci-app-smartinfo/luasrc/view/admin_status/index/smartinfo.htm
- applications/luci-app-smartinfo/luasrc/view/smartinfo/detail_begin_flag.htm
- applications/luci-app-smartinfo/luasrc/view/smartinfo/detail_begin_value.htm
- applications/luci-app-smartinfo/luasrc/view/smartinfo/detail_end_listvalue.htm
- applications/luci-app-smartinfo/luasrc/view/smartinfo/detail_end_value.htm
- applications/luci-app-smartinfo/luasrc/view/smartinfo/smart_detail.htm
- applications/luci-app-smartinfo/luasrc/view/smartinfo/smart_status.htm
- applications/luci-app-smartinfo/po/zh-cn/smartinfo.po
- applications/luci-app-smartinfo/root/etc/config/smartinfo
- applications/luci-app-smartinfo/root/etc/init.d/smartinfo
- applications/luci-app-smartinfo/root/usr/lib/smartinfo/smart_checker.sh
- applications/luci-app-smartinfo/root/usr/lib/smartinfo/smart_functions.sh
- applications/luci-app-smartinfo/root/usr/lib/smartinfo/smart_status.sh
view disk information, including temperature, total writes data and 0E warning.
> Add luci-app-smartinfo

- applications/luci-app-openlist/Makefile
- applications/luci-app-openlist/htdocs/luci-static/resources/view/openlist/config.js
- applications/luci-app-openlist/htdocs/luci-static/resources/view/openlist/log.js
- applications/luci-app-openlist/po/templates/openlist.pot
- applications/luci-app-openlist/po/zh_Hans/openlist.po
- applications/luci-app-openlist/root/usr/share/luci/menu.d/luci-app-openlist.json
- applications/luci-app-openlist/root/usr/share/rpcd/acl.d/luci-app-openlist.json
https://github.com/coolsnowwolf/packages/pull/955
> [openwrt-24.10]luci-app-openlist: add new package

- applications/luci-app-openlist/Makefile
- applications/luci-app-openlist/htdocs/luci-static/resources/view/openlist/config.js
- applications/luci-app-openlist/htdocs/luci-static/resources/view/openlist/log.js
- applications/luci-app-openlist/po/templates/openlist.pot
- applications/luci-app-openlist/po/zh_Hans/openlist.po
- applications/luci-app-openlist/root/usr/share/luci/menu.d/luci-app-openlist.json
- applications/luci-app-openlist/root/usr/share/rpcd/acl.d/luci-app-openlist.json
https://github.com/coolsnowwolf/packages/pull/955
> [openwrt-23.05]luci-app-openlist: add new package
